### ISSUE TITLE
upgrade script does not handle long node name properly

### ISSUE THREAD

**Issue by maximvl** [rebar/rebar#133]
Node runner script does not respect name type in vm.args and runs ```install_upgrade.escript``` which itself only works with shortnames, and finally tries to start node with name like ```node@127.0.0.1_upgrader_18328``` and of course fails.

**Comment by seriyps** [comment]
Hi.

This issue is still actual and can be reproduced by just following https://github.com/rebar/rebar/wiki/Upgrades up to (not including) "Deploying with release_handler" and running instead
```
mv dummy_0.2.tar.gz dummy_0.1/releases/
dummy_0.1/bin/upgrade dummy_0.2
```

The key pre-requisite is vm.args file should contain `-name <name>@<host>`, not `-sname <name>`!

So, steps are:

* vm.args file should contain `-name <name>@<host>`, not `-sname <name>`
* `./bin/<name> start` should be started using this vm.args
* release upgrade should be generated by `rebar generate-appups` `rebar generate-upgrade` or in some other way
* you should try to apply this upgrade using rebar-generated helper `./bin/<name> upgrade <name>_<version>`

It will fall with 
```
=INFO REPORT==== 8-Jan-2015::19:35:58 ===
Can't set short node name!
Please check your configuration
escript: exception error: no match of right hand side value 
                 {error,
                     {{shutdown,
                          {failed_to_start_child,net_kernel,
                              {'EXIT',nodistribution}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['dummy@127.0.0.1_upgrader_21087',shortnames]]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}

```

So, issue is in https://github.com/rebar/rebar/blob/master/priv/templates/simplenode.install_upgrade.escript#L34-L52
It forces shortnames by `net_kernel:start([MyNode, shortnames])` and generate improper node name: `dummy@127.0.0.1_upgrader_21087` instead of `dummy_upgrader_21087@127.0.0.1`.

Suggested solution:
fix `make_script_node` to generate proper node name and fix `start_distribution` to use short or long node name depending on presence of `@` in `NodeName`.

**Comment by ferd** [comment]
The thing could probably use a proper shortname if it used something like `dummy_upgrader21087@localhost` instead of `127.0.0.1`, which is a FQDN and requires long names.

**Comment by seriyps** [comment]
@ferd I think upgrade functionality from https://github.com/rebar/rebar/blob/master/priv/templates/simplenode.install_upgrade.escript should be moved to https://github.com/rebar/rebar/blob/master/priv/templates/simplenode.nodetool , which already supports `-name` / `-sname` and other options.

**Comment by seriyps** [comment]
@ferd I'll make a pull-request, which moves hot upgrade functionality to nodetool

**Comment by tsloughter** [comment]
@seriyps you may want to instead look at the relx templates that have gone through a lot of improvements https://github.com/erlware/relx/tree/master/priv/templates

**Comment by seriyps** [comment]
@tsloughter yeah, interesting. I think I first just copy current functionality (to fix bug) and, next, maybe apply relx improevements of install_upgrade.escript

P.S.: relx install_upgrade.escript has the same bug, but it forces longnames, while rebar forces shortnames!

**Comment by seriyps** [comment]
So, #426

**Comment by tuncer** [comment]
@seriyps wrote:
> next, maybe apply relx improevements of install_upgrade.escript

Good idea!
