### ISSUE TITLE
update-deps now does not work with pre_hooks

### ISSUE THREAD

**Issue by okeuday** [rebar/rebar#159]
This is a problem that occurs at (or possibly before) commit ed88055a750736c5c9807ca4da4803ff8a6aef16 .  The update-deps command no longer runs pre_hooks like it did previously (at commit 620c4b01c6e59d47e92ea069f8510b8cb482ebae and afterwards).  An example of this problem is at https://github.com/CloudI/CloudI/tree/develop/examples/hello_world3 .  update-deps is being used here to recompile/install a raw dep.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
