### ISSUE TITLE
Generated .cmd file always insists on using -sname rather than -name

### ISSUE THREAD

**Issue by colefichter** [rebar/rebar#169]
I'm not sure if this is a bug or just unclear documentation.  I've generated a node called "dummynode". I want to use long node names (-name) so that I can distribute a cluster across physical machines.

The generated vm.args file contains a section like:

```
## Name of the node
-name dummynode@127.0.0.1
```

From the looks of it, you'd think that I could change it to something like 

```
-name mynode@mydomain.com
```

And have the service started with long names enabled.  However, looking in the generated dummynode.cmd file, it always invokes the erlang runtime with the -sname flag, which means I can't distribute my application without manually changing the command files.

Perhaps change the generated .cmd file to pull the entire -name line from vm.args and use that to launch the runtime?  That way the developer can choose to use either long or short names when running the application.

Thanks!

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
