### ISSUE TITLE
update-deps dependency conflict

### ISSUE THREAD

**Issue by archaelus** [rebar/rebar#170]
I frequently want to modify the dependencies of my project (fork and modify them). This is fine for direct dependencies, but seems to cause a problem with `update-deps` if I modify an indirect dependency (a dependency of a dependency in this case (ranch from cowboy)). In order to force this override, I make the dep/dep (ranch) a direct dependency of the top level project. At this point `get-deps` works, but `update-deps` doesn't.

I think a direct dependency should override indirect dependencies. Maybe warn that there's a version conflict, but my top-level choice should always beat an indirect one.

Failing that, I don't know how I would be able to modify ranch without also modifying cowboy to choose my modified ranch as well.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
