### ISSUE TITLE
Upgrade script does not work with slim releases yet

### ISSUE THREAD

**Issue by shino** [rebar/rebar#202]
Gleaning issue from #52 .

Upgrading with slim release can be done if we do it **manually**.
1.   unpack relup archive manually
2.   copy `releases` directory and necessary libraries
3.   using release_hander:set_unpacked/2 .

Slim release is a experimental feature of reltool and release_handler does not know
about it at all (at least R16B03). So relup archive includes erts and all libraries in OTP,
we need to select necessary libraries in step 2, 
(These steps are illustrated at https://github.com/shino/slim-upgrade-sample ) 

These steps might possibly be automated by slim-release-aware
`install_upgrade` escript.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
