### ISSUE TITLE
Rebar passes the wrong filepath to the plugin handlers

### ISSUE THREAD

**Issue by AeroNotix** [rebar/rebar#238]
``` erlang

foo({config, D, Config, _, _, _, _}, AppFile) ->
    io:format("~p~n", [D]),
    ok.
```

This is NOT the same as file:get_cwd(), since rebar sets the cwd before calling the plugin cwd is set correctly, but the actual filepath is not. This means that it's useless to receive D or AppFile.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
