### ISSUE TITLE
Add 'svn url' command

### ISSUE THREAD

**Issue by lispking** [rebar/rebar#256]
diff --git a/src/rebar_deps.erl b/src/rebar_deps.erl
index 5e69709..492079a 100644
--- a/src/rebar_deps.erl
+++ b/src/rebar_deps.erl
@@ -514,6 +514,11 @@ download_source(AppDir, {bzr, Url, Rev}) ->
     rebar_utils:sh(?FMT("bzr branch -r ~s ~s ~s",
                         [Rev, Url, filename:basename(AppDir)]),
                    [{cd, filename:dirname(AppDir)}]);
+download_source(AppDir, {svn, Url}) ->
-    ok = filelib:ensure_dir(AppDir),
-    rebar_utils:sh(?FMT("svn checkout ~s ~s",
-                        [Url, filename:basename(AppDir)]),
-                   [{cd, filename:dirname(AppDir)}]);
  download_source(AppDir, {svn, Url, Rev}) ->
     ok = filelib:ensure_dir(AppDir),
     rebar_utils:sh(?FMT("svn checkout -r ~s ~s ~s",

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
