### ISSUE TITLE
rebar does not work if folder is not version controled

### ISSUE THREAD

**Issue by fenollp** [rebar/rebar#259]
## Reproduce
- `git clone git@github.com:erlydtl/erlydtl.git erlydtl.git`, for instance.
- `cd erlydtl.git && make` -- this will **work**, however…
- `rm -rf .git && make` -- this will **fail**.
## Error displayed

``` shell
ERROR: git describe --always --tags failed with error: 128 and output:
fatal: Not a git repository (or any of the parent directories): .git
```
## Cause

It seems that a call to `vcs_vsn_invoke/2` fails. Apparently rebar calls https://github.com/rebar/rebar/blob/master/src/rebar_utils.erl#L480 even if no `.git` directory exists.
## Solution

I'm looking into it.

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
