### ISSUE TITLE
Plugins, Environments and Duplicates

### ISSUE THREAD

**Issue by robertoaloi** [rebar/rebar#261]
The `rebar_core:setup_envs/2` function can lead by design to multiple entries in the environment.

To circumvent part of the problem, in #98 the `rebar_port_compiler` plugin is prevented from emitting the same environment variables emitted by `rebar_deps`, to avoid duplicates. This looks to me like a palliative and not like a definitive solution, since it requires a plugin to have too much information about other plugins. Maybe plugins should be given the possibility to `teardown_env`, in the same way as they can `setup_env`, maybe they should not be able to modify the `Env` at all. In #98 @jcomellas has a good point about the order of precedence among plugins when modifying the environment.

Opinions?

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
