### ISSUE TITLE
ct_extra_params doesn't work with Mac OS 10.10

### ISSUE THREAD

**Issue by Prots** [rebar/rebar#422]
Hi to all!

I can't run normally my common test because rebar doesn't recognize app.config file in ct_extra_params tuple. 
{ct_extra_params, "-pa deps/*/ebin -s app_name -config app.config"}.

When I try to run this CT on Linux - it works!

Now I was copied app.config to test directory and start application in function init_per_suite/1 and CT run normally, but it's bad practice - support two config files in the different places, I think.

Help me please!

**Comment by tuncer** [comment]
I don't have access to OS X. @ferd, any idea? Could it be the glob?

**Comment by ferd** [comment]
I can try it if I get an access to a similar repo. @Prots do you have any open source code to simulate this, or would I have to reimplement dummy suites and apps for this?

Have you also tried `-config app` instead of `-config app.config` ? Erlang's `erl` appears to do some dynamic matching where it picks whether to add or not the trailing `.config`, but maybe this is being lost in CT.

**Comment by Prots** [comment]
Guys, the problem was solved. The next string works:
{ct_extra_params, "-erl_args -pa deps/*/ebin -config app.config -s app_name"}.

As I understand, CT think that I got him name of his config file, not app config.

**Comment by tuncer** [comment]
Can this be closed as RESOLVED?
