### ISSUE TITLE
generate `applications` fields in the output `.app` file from rebar dependency list?

### ISSUE THREAD

**Issue by csyangchen** [rebar/rebar#528]
In my use case, I need to add every dependent non-otp application to both rebar.config deps and .app.src applications field.

Any thoughts on how to do this, or any reasons against this practice?

**Comment by ferd** [comment]
What is a dependent non-otp application?

**Comment by csyangchen** [comment]
`non-otp applications` means applications not provided by otp-release.

For example. 

In myapp.app.src file:

```
{..., applications, [kernel, stdlib, crypto, dep_app1, dep_app2, ...]}, ...}
```

In my rebar.config file:
```
{deps, [
    {dep_app1, ...},
    {dep_app2, ...},
    ...
]}
```

I need to update the `dep_app1`, `dep_app2`, ... list in both places.

**Comment by ferd** [comment]
We shouldn't generate these apps from the dependency list, because there is the possibility that a rebar project has more than one application. Say for example:

```
apps/
 - app_a/
 - app_b/
test/
 - ...
rebar.config
```
In such a project, it is very possible that `app_a` depends on `dep_app1`, and `app_b` depends on `dep_app2` *and* `app_a`. If we put all deps in the same list, things might work, but in many scenarios (such as tests), you'll now need to start `dep_app2` when testing `app_a` despite never actually requiring it.

You also have the case where you have a dependency for your project that you only need to debug live systems (such as `recon` or `redbug`) or tests (`meck` or `PropEr` or quickcheck). In this case you may want to have them available, but you won't want your application to depend on them to be able to run in production.

There's still more cases, such as compile-time plugins, which in this generation of rebar, are declared as dependencies. Once again, you could be forced to boot a compiler plugin for your application to run in production, which is not great.

The deps in the list can represent the deps of the whole *project*, but the `{applications, [....]}` list represents the dependencies of that *application*. They often overlap, but they are not the same, and auto-generating them is not the best of ideas in general.

**Comment by csyangchen** [comment]
Now I know better. Thanks for your detailed clarifications.
