### ISSUE TITLE
can I generate release from Windows to use on Linux?

### ISSUE THREAD

**Issue by sparktwinny** [rebar/rebar#577]
It works on windows, but for example can I copy and paste release file to linux and run it ?

**Comment by ferd** [comment]
You can only do so if the release uses the Linux Erlang runtime system. These files (basically the VM) are not portable. The same caveat also applies to drivers, NIFs, and other C code that could be compiled.

Basically, only standard .beam files are portable in that whole thing, so if your release only needs *these*, it should work fine. Otherwise, it won't be enough and you'll need to cross-compile or have the linux host be ready to provide some of the required files.

**Comment by lrascao** [comment]
Closing, @sparktwinny please re-open if anymore doubts still persist
