### ISSUE TITLE
escript: exception error: undefined function make:files/2 

### ISSUE THREAD

**Issue by oladipo** [rebar/rebar#600]
When i try to run ./bootstrap to install rebar I get the following error:

oladipo@ubuntu:~/basho/rebar$ ./bootstrap
escript: exception error: undefined function make:files/2
  in function  erl_eval:do_apply/5
  in call from erl_eval:expr/5
  in call from escript:eval_exprs/5
  in call from erl_eval:local_func/5
  in call from escript:interpret/3
  in call from escript:start/1
  in call from init:start_it/1

**Comment by tuncer** [comment]
How did you install Erlang/OTP? It looks like some modules (and apps) are missing, specifically the tools app, which contains make.beam. `make:files/2` has been exported in `otp/lib/tools/src/make.erl` since at least R13B03 (and likely earlier), so it's safe to assume make.beam cannot be found. If you installed Erlang from a repository that split it into several packages, make sure to install the package that contains the tools app.

Hence, your incomplete Erlang install will behave as follows, until you've installed the missing app:
```
> code:which(make).
non_existing
```

**Comment by oladipo** [comment]
You are correct. Installed erlang and rebar on a different machine. No issues this time. Thanks
