### ISSUE TITLE
tags/branches selected on an initial get-deps do not match subsequent get-deps

### ISSUE THREAD

**Issue by DeadZen** [rebar/rebar#86]
For instance, if you have a dependency specifying a tag, it may download the dependency with that tag. If you delete that application, rm -rf deps/app, and then get-deps again..

It may not go to that tag again, it may go to the master branch.. I'm not sure if this is in effect due to config inheritance.. but this behaviour should always have the same outcome, regardless of whether it's the first get-deps or a subsequent get-deps operation.

A possible solution is for an initial get-deps operation to create a dependency graph and on subsequent get-deps walk that graph, possibly looking for changes, this would assure the exact same outcome in either case and not rely on any configuration inherited which may unpredictably override tag/branch specifications in a base application to favor a dependency specification from a dep.    

To clarify, say for example I specify  
{deps, [ {lager, "(2.0|1.0|1.2)._", ... {branch, "master"} ] in a dependency
I'm saying in effect, any 2.0._, 1.0._, or 1.2._ tag is alright, otherwise choose master however this is just a dependency, it should not have an overriding decision on what specific branch/tag of lager the base application requests.. it is just declaring it is needed and what versions are compatible.. 

And in the base application specify {lager, "2.0.0", ... {tag, "2.0.0"} ] in rebar.config's deps, then delete deps/lager and subsequently do a get-deps.. 

It will likely pull out the correct tag on the initial get-deps (2.0.0) then erroneously grab the master branch on the next invocation of get-deps if the deps/lager app is deleted.. 

This unpredictable behavior is highly undesirable...

**Comment by lrascao** [comment]
Hi, this issue was closed in an attempt to do quick basic filtering. These issues and pull requests are not issues or code we're spitting on, but given the burden of the task and how much code rot may have happened since these were open is unknown from maintainers at this time. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give
rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.
